[package]
name = "debunk-this"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.1"
rig-core = "0.9.1"
schemars = "0.8.22"
ytranscript = "0.1.0"
tokio = { version = "1.44.0", features = ["full"] }
serde = "1.0.219"
serde_json = "1.0.140"
thiserror = "2.0.12"
anyhow = "1.0.97"
