version: '3.8'

services:
  db:
    image: postgres:16-alpine
    restart: always
    container_name: debunk_this_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init/postgres:/docker-entrypoint-initdb.d

volumes:
  pgdata: