@DebunkThis_HostAddress = http://localhost:3000
@video_id = CINrLeFJBu4

GET {{DebunkThis_HostAddress}}/api/synthesize/{{video_id}}/transcript
Accept: application/json

###
GET {{DebunkThis_HostAddress}}/api/synthesize/{{video_id}}
Accept: application/json